#include <Key.h>
#include <Keypad.h>

#define WhiteTree 29
#define BlueTree 26
#define Blues 22
#define Whites 24
#define MultiTop 25
#define Wreaths 23
#define Red 28
#define MultiArch 25

#define SPKROFF 53


const byte numRows= 4; //number of rows on the keypad
const byte numCols= 4; //number of columns on the keypad

//keymap defines the key pressed according to the row and columns just as appears on the keypad
char keymap[numRows][numCols]= 
{
{'1', '2', '3', 'A'}, 
{'4', '5', '6', 'B'}, 
{'7', '8', '9', 'C'},
{'*', '0', '#', 'D'}
};

//Code that shows the the keypad connections to the arduino terminals
byte rowPins[numRows] = {47, 46, 45, 44}; //connect to the row pinouts of the keypad
byte colPins[numCols] = {43, 42, 41, 40}; //connect to the column pinouts of the keypad
Keypad keypad = Keypad( makeKeymap(keymap), rowPins, colPins, numRows, numCols );

int input;
boolean hasInput;
int numChs = 8;
int startDelay = 0;
double lagMod = 1.0;
boolean playMusic = true;
boolean speakersOn = false;

int count = 0; //Counts input digits
int *digits; //Points to array of input digits

String inputString = "";         // a string to hold incoming data

const int chs[] = {WhiteTree, BlueTree, Blues, Whites, MultiTop, Wreaths, Red, MultiArch};



void setup() {
  Serial.begin(9600);
  Serial1.begin(9600);
    
  pinMode(SPKROFF, OUTPUT);

  
  for(int i=0; i<numChs; i++){
    pinMode(chs[i], OUTPUT);
}

Serial.print("Setup Complete");
}

void loop() {
  
 //look for input
char keypressed = keypad.getKey();
if (keypressed != NO_KEY)
{
Serial.println(keypressed);
int keyToInt = keypressed - '0';
if(keyToInt > 0 && keyToInt <= numChs){
  toggle(chs[keyToInt-1]);
 }
if(keypressed == 'A'){
  plaxXmasEve();
}
else if(keypressed == 'B'){
  playFrozen();
}

else if(keypressed == 'C'){
  countdown();
  playPains();
}
}
 
  // if there's any serial available, read it:
  while (Serial.available() > 0) {

    // look for the next valid integer in the incoming serial stream:
    int input = Serial.parseInt();

    // look for the newline. That's the end of your
    // sentence:
    if (Serial.read() == '\n') {
 if(input != -1 && input <= numChs){
  toggle(chs[input-1]);
 }
    }
}
}


void flashAll(double time){
  for(int i=0; i<numChs; i++){
    digitalWrite(chs[i], HIGH);
  }
  delay(time);
  for(int i=0; i<numChs; i++){
    digitalWrite(chs[i], LOW);
  }
  delay(time);
}


//Methods for blinking LEDs. Paramaters: Count = number of times led should flash; delayTime = How flast led should blink in millis
//void blinkRed(int count, int delayTime) {
//  for (int i=0; i<count; i++) {
//    digitalWrite(redLED, HIGH);
//    delay(delayTime/2);
//    digitalWrite(redLED, LOW);
//    delay(delayTime/2);
//  }
//}

//void blinkYellow(int count, int delayTime){
//  for (int i=0; i<count; i++) {
//    digitalWrite(yellowLED, HIGH);
//    delay(delayTime/2);
//    digitalWrite(yellowLED, LOW);
//    delay(delayTime/2);
//
//  }
//}
//
//void blinkGreen(int count, int delayTime) {
//  for (int i=0; i<count; i++) {
//    digitalWrite(greenLED, HIGH);
//    delay(delayTime/2);
//    digitalWrite(greenLED, LOW);
//    delay(delayTime/2);
//  }
//}

void toggle(int ch){
  digitalWrite(ch, !(digitalRead(ch)));
}

void countdown() {
  Serial.println("Starting...");
  for (int i = 0; i<10; i++){
    Serial.println(10-i);
    delay(1000);
  }
  Serial.println("GO!");
}

void plaxXmasEve() {
    Serial.println("Playing Christmas Eve Sarajevo");

  if(playMusic){
  Serial1.print(1);
  Serial.println("Song started");
//  while(Serial1.available() <= 0) {
//  }
  int responseInt = Serial1.parseInt();
  Serial.println("Response: ");
  Serial.println(responseInt);
  
  if(speakersOn){
    digitalWrite(SPKROFF, HIGH);
  }
  else {
    digitalWrite(SPKROFF, LOW);
  }
}
delay(0.0 * lagMod);
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, LOW);
digitalWrite(Blues, LOW);
digitalWrite(Whites, LOW);
digitalWrite(MultiTop, LOW);
digitalWrite(Wreaths, LOW);
digitalWrite(Red, LOW);
digitalWrite(MultiArch, LOW);
Serial.println("Cue: 0.0");
delay(3020.0 * lagMod);
digitalWrite(BlueTree, HIGH);
digitalWrite(Blues, HIGH);
Serial.println("Cue: 3.02");
delay(28680.0 * lagMod);
digitalWrite(BlueTree, LOW);
digitalWrite(Blues, LOW);
Serial.println("Cue: 31.7");
delay(3200.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(Whites, HIGH);
digitalWrite(Wreaths, HIGH);
digitalWrite(Red, HIGH);
Serial.println("Cue: 34.9");
delay(400.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(580.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(50.0 * lagMod);
digitalWrite(Wreaths, LOW);
digitalWrite(Whites, LOW);
Serial.println("Cue: 35.93");
delay(350.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(580.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(580.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(580.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(580.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(580.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(580.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(580.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(100.0 * lagMod);
digitalWrite(Wreaths, HIGH);
digitalWrite(BlueTree, HIGH);
digitalWrite(WhiteTree, LOW);
digitalWrite(Blues, HIGH);
digitalWrite(MultiArch, HIGH);
Serial.println("Cue: 42.84");
delay(3760.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(BlueTree, LOW);
Serial.println("Cue: 46.6");
delay(700.0 * lagMod);
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, HIGH);
Serial.println("Cue: 47.3");
delay(3290.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(BlueTree, LOW);
Serial.println("Cue: 50.59");
delay(710.0 * lagMod);
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, HIGH);
Serial.println("Cue: 51.3");
delay(3180.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(BlueTree, LOW);
Serial.println("Cue: 54.48");
delay(720.0 * lagMod);
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, HIGH);
Serial.println("Cue: 55.2");
delay(2950.0 * lagMod);
digitalWrite(MultiTop, HIGH);
Serial.println("Cue: 58.15");
delay(600.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(352.0 * lagMod);
digitalWrite(MultiTop, HIGH);
delay(600.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(352.0 * lagMod);
digitalWrite(MultiTop, HIGH);
delay(600.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(352.0 * lagMod);
digitalWrite(MultiTop, HIGH);
delay(600.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(352.0 * lagMod);
digitalWrite(MultiTop, HIGH);
delay(162.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
Serial.println("Cue: 62.12");
delay(438.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(352.0 * lagMod);
digitalWrite(MultiTop, HIGH);
delay(600.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(352.0 * lagMod);
digitalWrite(MultiTop, HIGH);
delay(600.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(352.0 * lagMod);
digitalWrite(MultiTop, HIGH);
delay(600.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(352.0 * lagMod);
digitalWrite(MultiTop, HIGH);
delay(144.0 * lagMod);
digitalWrite(MultiTop, LOW);
digitalWrite(Whites, HIGH);
digitalWrite(Blues, LOW);
digitalWrite(WhiteTree, LOW);
Serial.println("Cue: 65.91");
delay(186.0 * lagMod);
digitalWrite(Whites, LOW);
delay(186.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(186.0 * lagMod);
digitalWrite(Whites, LOW);
delay(186.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(186.0 * lagMod);
digitalWrite(Whites, LOW);
delay(30.0 * lagMod);
digitalWrite(MultiTop, HIGH);
digitalWrite(Whites, LOW);
Serial.println("Cue: 66.87");
delay(186.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(186.0 * lagMod);
digitalWrite(MultiTop, HIGH);
delay(186.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(186.0 * lagMod);
digitalWrite(MultiTop, HIGH);
delay(186.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(100.0 * lagMod);
digitalWrite(MultiTop, LOW);
digitalWrite(Blues, HIGH);
Serial.println("Cue: 67.9");
delay(186.0 * lagMod);
digitalWrite(Blues, LOW);
delay(186.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(186.0 * lagMod);
digitalWrite(Blues, LOW);
delay(186.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(186.0 * lagMod);
digitalWrite(Blues, LOW);
delay(186.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(186.0 * lagMod);
digitalWrite(Blues, LOW);
delay(186.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(186.0 * lagMod);
digitalWrite(Blues, LOW);
delay(186.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(130.0 * lagMod);
digitalWrite(Whites, HIGH);
digitalWrite(Blues, LOW);
digitalWrite(Red, LOW);
Serial.println("Cue: 69.89");
delay(1810.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(Wreaths, HIGH);
digitalWrite(Whites, LOW);
Serial.println("Cue: 71.7");
delay(2000.0 * lagMod);
digitalWrite(MultiTop, HIGH);
Serial.println("Cue: 73.7");
delay(1080.0 * lagMod);
digitalWrite(BlueTree, HIGH);
digitalWrite(Blues, HIGH);
Serial.println("Cue: 74.78");
delay(860.0 * lagMod);
digitalWrite(Red, HIGH);
Serial.println("Cue: 75.64");
delay(1800.0 * lagMod);
digitalWrite(Whites, HIGH);
Serial.println("Cue: 77.44");
delay(560.0 * lagMod);
digitalWrite(MultiTop, LOW);
Serial.println("Cue: 78.0");
delay(280.0 * lagMod);
digitalWrite(MultiArch, LOW);
Serial.println("Cue: 78.28");
delay(320.0 * lagMod);
digitalWrite(Whites, LOW);
Serial.println("Cue: 78.6");
delay(320.0 * lagMod);
digitalWrite(Wreaths, LOW);
Serial.println("Cue: 78.92");
delay(320.0 * lagMod);
digitalWrite(Red, LOW);
Serial.println("Cue: 79.24");
delay(320.0 * lagMod);
digitalWrite(Blues, LOW);
Serial.println("Cue: 79.56");
delay(320.0 * lagMod);
digitalWrite(WhiteTree, LOW);
Serial.println("Cue: 79.88");
delay(320.0 * lagMod);
digitalWrite(BlueTree, LOW);
Serial.println("Cue: 80.2");
delay(1180.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(Whites, HIGH);
digitalWrite(Wreaths, HIGH);
digitalWrite(MultiTop, HIGH);
Serial.println("Cue: 81.38");
delay(3920.0 * lagMod);
digitalWrite(WhiteTree, LOW);
digitalWrite(Whites, LOW);
digitalWrite(Wreaths, LOW);
digitalWrite(Blues, HIGH);
digitalWrite(BlueTree, HIGH);
digitalWrite(MultiTop, LOW);
Serial.println("Cue: 85.3");
delay(3700.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(Whites, HIGH);
digitalWrite(Wreaths, HIGH);
digitalWrite(BlueTree, LOW);
digitalWrite(Blues, LOW);
digitalWrite(MultiTop, HIGH);
Serial.println("Cue: 89.0");
delay(3900.0 * lagMod);
digitalWrite(BlueTree, HIGH);
digitalWrite(WhiteTree, LOW);
digitalWrite(Whites, LOW);
digitalWrite(Wreaths, LOW);
digitalWrite(Blues, HIGH);
digitalWrite(MultiTop, LOW);
Serial.println("Cue: 92.9");
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(40.0 * lagMod);
digitalWrite(Wreaths, HIGH);
digitalWrite(MultiArch, HIGH);
Serial.println("Cue: 104.4");
delay(360.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
Serial.println("Cue: 112.0");
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(555.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(200.0 * lagMod);
digitalWrite(BlueTree, HIGH);
digitalWrite(MultiTop, LOW);
digitalWrite(Red, HIGH);
digitalWrite(Wreaths, LOW);
digitalWrite(Blues, LOW);
digitalWrite(MultiArch, LOW);
Serial.println("Cue: 119.84");
delay(700.0 * lagMod);
digitalWrite(Red, LOW);
delay(254.0 * lagMod);
digitalWrite(Red, HIGH);
delay(700.0 * lagMod);
digitalWrite(Red, LOW);
delay(254.0 * lagMod);
digitalWrite(Red, HIGH);
delay(700.0 * lagMod);
digitalWrite(Red, LOW);
delay(254.0 * lagMod);
digitalWrite(Red, HIGH);
delay(700.0 * lagMod);
digitalWrite(Red, LOW);
delay(254.0 * lagMod);
digitalWrite(Red, HIGH);
delay(700.0 * lagMod);
digitalWrite(Red, LOW);
delay(254.0 * lagMod);
digitalWrite(Red, HIGH);
delay(700.0 * lagMod);
digitalWrite(Red, LOW);
delay(254.0 * lagMod);
digitalWrite(Red, HIGH);
delay(700.0 * lagMod);
digitalWrite(Red, LOW);
delay(254.0 * lagMod);
digitalWrite(Red, HIGH);
delay(700.0 * lagMod);
digitalWrite(Red, LOW);
delay(254.0 * lagMod);
digitalWrite(Red, HIGH);
delay(48.0 * lagMod);
digitalWrite(Blues, HIGH);
digitalWrite(Red, LOW);
Serial.println("Cue: 127.52");
delay(3980.0 * lagMod);
digitalWrite(MultiTop, HIGH);
Serial.println("Cue: 131.5");
delay(3700.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
Serial.println("Cue: 135.2");
delay(600.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(352.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(600.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(352.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(600.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(352.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(600.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(352.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(42.0 * lagMod);
digitalWrite(Wreaths, HIGH);
digitalWrite(Red, HIGH);
Serial.println("Cue: 139.05");
delay(558.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(352.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(600.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(352.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(600.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(352.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(600.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(352.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(244.0 * lagMod);
digitalWrite(Whites, HIGH);
digitalWrite(MultiTop, LOW);
Serial.println("Cue: 143.06");
delay(186.0 * lagMod);
digitalWrite(Whites, LOW);
delay(170.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(16.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(186.0 * lagMod);
digitalWrite(Whites, LOW);
delay(150.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(36.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(186.0 * lagMod);
digitalWrite(Whites, LOW);
delay(10.0 * lagMod);
digitalWrite(Whites, LOW);
digitalWrite(MultiTop, HIGH);
Serial.println("Cue: 144.0");
delay(186.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(182.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(4.0 * lagMod);
digitalWrite(MultiTop, HIGH);
delay(186.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(162.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(24.0 * lagMod);
digitalWrite(MultiTop, HIGH);
delay(186.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(80.0 * lagMod);
digitalWrite(WhiteTree, LOW);
Serial.println("Cue: 145.01");
delay(10.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(MultiTop, LOW);
Serial.println("Cue: 145.02");
delay(186.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(186.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(186.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(186.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(186.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(50.0 * lagMod);
digitalWrite(WhiteTree, LOW);
Serial.println("Cue: 146.0");
delay(450.0 * lagMod);
digitalWrite(WhiteTree, LOW);
Serial.println("Cue: 146.45");
delay(370.0 * lagMod);
digitalWrite(BlueTree, LOW);
digitalWrite(Blues, LOW);
digitalWrite(Whites, LOW);
digitalWrite(MultiTop, LOW);
digitalWrite(Wreaths, LOW);
digitalWrite(Red, LOW);
digitalWrite(MultiArch, LOW);
digitalWrite(WhiteTree, HIGH);
Serial.println("Cue: 146.82");
delay(1920.0 * lagMod);
digitalWrite(WhiteTree, LOW);
digitalWrite(Wreaths, HIGH);
digitalWrite(MultiArch, HIGH);
Serial.println("Cue: 148.74");
delay(1930.0 * lagMod);
digitalWrite(Wreaths, LOW);
digitalWrite(MultiArch, LOW);
digitalWrite(BlueTree, HIGH);
digitalWrite(Blues, HIGH);
Serial.println("Cue: 150.67");
delay(1090.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(MultiTop, HIGH);
digitalWrite(BlueTree, LOW);
digitalWrite(Blues, LOW);
digitalWrite(Whites, HIGH);
Serial.println("Cue: 151.76");
delay(970.0 * lagMod);
digitalWrite(WhiteTree, LOW);
digitalWrite(MultiTop, LOW);
digitalWrite(BlueTree, HIGH);
digitalWrite(Blues, HIGH);
digitalWrite(Whites, LOW);
Serial.println("Cue: 152.73");
delay(920.0 * lagMod);
digitalWrite(MultiTop, HIGH);
digitalWrite(Whites, HIGH);
Serial.println("Cue: 153.65");
delay(1000.0 * lagMod);
digitalWrite(Wreaths, HIGH);
Serial.println("Cue: 154.65");
delay(950.0 * lagMod);
digitalWrite(MultiArch, HIGH);
Serial.println("Cue: 155.6");
delay(900.0 * lagMod);
digitalWrite(Red, HIGH);
Serial.println("Cue: 156.5");
delay(700.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
Serial.println("Cue: 157.2");
delay(1300.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(Whites, HIGH);
Serial.println("Cue: 158.5");
delay(186.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(114.0 * lagMod);
digitalWrite(Whites, LOW);
delay(72.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(186.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(186.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(186.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(2.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(184.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(116.0 * lagMod);
digitalWrite(Whites, LOW);
delay(70.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(186.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(186.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(186.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(4.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(182.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(118.0 * lagMod);
digitalWrite(Whites, LOW);
delay(68.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(186.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(186.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(186.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(6.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(180.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(120.0 * lagMod);
digitalWrite(Whites, LOW);
delay(66.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(186.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(186.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(186.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(8.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(72.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(MultiTop, HIGH);
digitalWrite(Wreaths, LOW);
digitalWrite(Red, LOW);
digitalWrite(MultiArch, LOW);
digitalWrite(Whites, LOW);
digitalWrite(BlueTree, LOW);
Serial.println("Cue: 162.3");
delay(1950.0 * lagMod);
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, HIGH);
Serial.println("Cue: 164.25");
delay(1850.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(BlueTree, LOW);
Serial.println("Cue: 166.1");
delay(1100.0 * lagMod);
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, HIGH);
Serial.println("Cue: 167.2");
delay(850.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(BlueTree, LOW);
Serial.println("Cue: 168.05");
delay(850.0 * lagMod);
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, HIGH);
Serial.println("Cue: 168.9");
delay(1100.0 * lagMod);
digitalWrite(Whites, HIGH);
digitalWrite(Wreaths, HIGH);
digitalWrite(MultiArch, HIGH);
Serial.println("Cue: 170.0");
delay(500.0 * lagMod);
digitalWrite(Whites, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(0.0 * lagMod);
digitalWrite(MultiArch, LOW);
delay(460.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(0.0 * lagMod);
digitalWrite(MultiArch, HIGH);
delay(500.0 * lagMod);
digitalWrite(Whites, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(0.0 * lagMod);
digitalWrite(MultiArch, LOW);
delay(460.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(0.0 * lagMod);
digitalWrite(MultiArch, HIGH);
delay(500.0 * lagMod);
digitalWrite(Whites, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(0.0 * lagMod);
digitalWrite(MultiArch, LOW);
delay(460.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(0.0 * lagMod);
digitalWrite(MultiArch, HIGH);
delay(470.0 * lagMod);
digitalWrite(MultiTop, HIGH);
Serial.println("Cue: 173.35");
delay(30.0 * lagMod);
digitalWrite(Whites, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(0.0 * lagMod);
digitalWrite(MultiArch, LOW);
delay(460.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(0.0 * lagMod);
digitalWrite(MultiArch, HIGH);
delay(10.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(460.0 * lagMod);
digitalWrite(MultiTop, HIGH);
delay(30.0 * lagMod);
digitalWrite(Whites, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(0.0 * lagMod);
digitalWrite(MultiArch, LOW);
delay(460.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(0.0 * lagMod);
digitalWrite(MultiArch, HIGH);
delay(10.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(460.0 * lagMod);
digitalWrite(MultiTop, HIGH);
delay(30.0 * lagMod);
digitalWrite(Whites, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(0.0 * lagMod);
digitalWrite(MultiArch, LOW);
delay(460.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(0.0 * lagMod);
digitalWrite(MultiArch, HIGH);
delay(10.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(460.0 * lagMod);
digitalWrite(MultiTop, HIGH);
delay(30.0 * lagMod);
digitalWrite(Whites, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(0.0 * lagMod);
digitalWrite(MultiArch, LOW);
delay(460.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(0.0 * lagMod);
digitalWrite(MultiArch, HIGH);
delay(10.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(460.0 * lagMod);
digitalWrite(MultiTop, HIGH);
delay(30.0 * lagMod);
digitalWrite(Whites, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(0.0 * lagMod);
digitalWrite(MultiArch, LOW);
delay(460.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(0.0 * lagMod);
digitalWrite(MultiArch, HIGH);
delay(10.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(60.0 * lagMod);
digitalWrite(Whites, LOW);
Serial.println("Cue: 177.75");
delay(10.0 * lagMod);
digitalWrite(Whites, HIGH);
digitalWrite(MultiArch, LOW);
digitalWrite(Wreaths, LOW);
digitalWrite(MultiTop, HIGH);
digitalWrite(WhiteTree, HIGH);
digitalWrite(BlueTree, LOW);
Serial.println("Cue: 177.76");
delay(200.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(111.0 * lagMod);
digitalWrite(Whites, LOW);
delay(89.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(200.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(22.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(178.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(133.0 * lagMod);
digitalWrite(Whites, LOW);
delay(67.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(200.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
Serial.println("Cue: 178.96");
delay(44.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(156.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(155.0 * lagMod);
digitalWrite(Whites, LOW);
delay(45.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(200.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(66.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(134.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(177.0 * lagMod);
digitalWrite(Whites, LOW);
delay(23.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(200.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(88.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(112.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(199.0 * lagMod);
digitalWrite(Whites, LOW);
delay(1.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(200.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(110.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(90.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(200.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(21.0 * lagMod);
digitalWrite(Whites, LOW);
delay(179.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(132.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(68.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(200.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(43.0 * lagMod);
digitalWrite(Whites, LOW);
delay(157.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(154.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(46.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(200.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(65.0 * lagMod);
digitalWrite(Whites, LOW);
delay(135.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(176.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(24.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(200.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(87.0 * lagMod);
digitalWrite(Whites, LOW);
delay(113.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(198.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(2.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(200.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(109.0 * lagMod);
digitalWrite(Whites, LOW);
delay(91.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(200.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(20.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(180.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(131.0 * lagMod);
digitalWrite(Whites, LOW);
delay(69.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(200.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(42.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(158.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(153.0 * lagMod);
digitalWrite(Whites, LOW);
delay(47.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(200.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(64.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(136.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(30.0 * lagMod);
digitalWrite(WhiteTree, LOW);
digitalWrite(Whites, LOW);
digitalWrite(BlueTree, LOW);
Serial.println("Cue: 185.39");
delay(10.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(BlueTree, LOW);
digitalWrite(Whites, HIGH);
digitalWrite(MultiTop, HIGH);
digitalWrite(Wreaths, HIGH);
digitalWrite(Red, HIGH);
digitalWrite(MultiArch, HIGH);
Serial.println("Cue: 185.4");
delay(500.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Whites, LOW);
delay(0.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(450.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(0.0 * lagMod);
digitalWrite(MultiTop, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(500.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Whites, LOW);
delay(0.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(450.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(0.0 * lagMod);
digitalWrite(MultiTop, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(500.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Whites, LOW);
delay(0.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(450.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(0.0 * lagMod);
digitalWrite(MultiTop, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(500.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Whites, LOW);
delay(0.0 * lagMod);
digitalWrite(MultiTop, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(450.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(0.0 * lagMod);
digitalWrite(MultiTop, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(50.0 * lagMod);
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, HIGH);
digitalWrite(Blues, HIGH);
digitalWrite(Red, HIGH);
digitalWrite(Whites, LOW);
digitalWrite(MultiTop, LOW);
digitalWrite(Wreaths, LOW);
digitalWrite(Red, LOW);
digitalWrite(MultiArch, LOW);
Serial.println("Cue: 189.25");
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(70.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(0.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(Whites, HIGH);
digitalWrite(Wreaths, HIGH);
digitalWrite(BlueTree, LOW);
digitalWrite(Blues, LOW);
digitalWrite(Red, LOW);
Serial.println("Cue: 193.1");
delay(1140.0 * lagMod);
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, HIGH);
digitalWrite(Whites, LOW);
digitalWrite(Wreaths, LOW);
Serial.println("Cue: 194.24");
}

void playFrozen() {
  Serial.println("Playing Let It Go");

  if(playMusic){
  Serial1.print(4);
  Serial.println("Song started");
//  while(Serial1.available() <= 0) {
//  }
  int responseInt = Serial1.parseInt();
  Serial.println("Response: ");
  Serial.println(responseInt);
  
  if(speakersOn){
    digitalWrite(SPKROFF, HIGH);
  }
  else {
    digitalWrite(SPKROFF, LOW);
  }
}
delay(0.0 * lagMod);
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, LOW);
digitalWrite(Blues, LOW);
digitalWrite(Whites, LOW);
digitalWrite(Wreaths, LOW);

digitalWrite(MultiArch, LOW);
digitalWrite(MultiTop, LOW);
digitalWrite(Red, LOW);
Serial.println("Cue: 0.0");
delay(8189.999999999999 * lagMod);
digitalWrite(BlueTree, HIGH);
Serial.println("Cue: 8.18");
delay(6810.000000000001 * lagMod);
digitalWrite(Wreaths, HIGH);
Serial.println("Cue: 15.0");
delay(14230.0 * lagMod);
digitalWrite(Blues, HIGH);
Serial.println("Cue: 29.23");
delay(7170.0 * lagMod);
digitalWrite(Wreaths, LOW);
digitalWrite(BlueTree, LOW);
Serial.println("Cue: 36.4");
delay(6600.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(Wreaths, LOW);
digitalWrite(BlueTree, LOW);
Serial.println("Cue: 43.0");
delay(3833.0 * lagMod);
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, HIGH);
Serial.println("Cue: 46.83");
delay(3529.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(BlueTree, LOW);
Serial.println("Cue: 50.36");
delay(10288.0 * lagMod);
digitalWrite(BlueTree, HIGH);
digitalWrite(WhiteTree, LOW);
digitalWrite(Blues, LOW);
Serial.println("Cue: 60.65");
delay(250.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(250.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(250.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(250.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(250.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(250.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(250.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(250.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(250.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(250.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(250.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(250.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(250.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(250.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(250.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(250.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(250.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(250.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(250.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(250.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(250.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(250.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(250.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(250.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(250.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(250.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(250.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(250.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(20.0 * lagMod);
digitalWrite(BlueTree, LOW);
digitalWrite(Wreaths, HIGH);
Serial.println("Cue: 67.67");
delay(250.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(250.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(250.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(250.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(250.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(250.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(250.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(250.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(250.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(250.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(250.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(250.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(250.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(250.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(250.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(250.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(250.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(250.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(250.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(250.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(250.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(250.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(250.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(250.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(250.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(250.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(250.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(250.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(180.0 * lagMod);
digitalWrite(Wreaths, LOW);
digitalWrite(BlueTree, HIGH);
Serial.println("Cue: 74.85");
delay(3420.0 * lagMod);
digitalWrite(Blues, HIGH);
Serial.println("Cue: 78.27");
delay(7030.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(Wreaths, LOW);
digitalWrite(Whites, HIGH);
digitalWrite(Blues, LOW);
digitalWrite(BlueTree, LOW);
Serial.println("Cue: 85.3");
delay(3660.0 * lagMod);
digitalWrite(BlueTree, HIGH);
digitalWrite(WhiteTree, LOW);
Serial.println("Cue: 88.96");
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(400.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(400.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(400.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(400.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(310.0 * lagMod);
digitalWrite(Wreaths, HIGH);
Serial.println("Cue: 92.47");
delay(90.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(400.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(400.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(400.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(400.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(400.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(400.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(400.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(400.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(400.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(90.0 * lagMod);
digitalWrite(Blues, HIGH);
digitalWrite(BlueTree, LOW);
Serial.println("Cue: 99.45");
delay(350.0 * lagMod);
digitalWrite(Blues, LOW);
delay(350.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(350.0 * lagMod);
digitalWrite(Blues, LOW);
delay(350.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(350.0 * lagMod);
digitalWrite(Blues, LOW);
delay(350.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(350.0 * lagMod);
digitalWrite(Blues, LOW);
delay(350.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(350.0 * lagMod);
digitalWrite(Blues, LOW);
delay(350.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(240.0 * lagMod);
digitalWrite(Blues, HIGH);
Serial.println("Cue: 103.19");
delay(3210.0 * lagMod);
digitalWrite(Wreaths, HIGH);
digitalWrite(WhiteTree, HIGH);
digitalWrite(Whites, LOW);
Serial.println("Cue: 106.4");
delay(7050.0 * lagMod);
digitalWrite(BlueTree, HIGH);
digitalWrite(WhiteTree, LOW);
Serial.println("Cue: 113.45");
delay(3590.0 * lagMod);
digitalWrite(Wreaths, HIGH);
digitalWrite(BlueTree, HIGH);
Serial.println("Cue: 117.04");
delay(400.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(0.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(400.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(0.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(400.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(0.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(400.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(400.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(0.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(260.0 * lagMod);
digitalWrite(BlueTree, HIGH);
digitalWrite(Wreaths, HIGH);
Serial.println("Cue: 120.1");
delay(140.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(10.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(150.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(150.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(90.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(0.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(60.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(150.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(150.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(40.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(110.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(150.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(140.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(0.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(10.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(150.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(150.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(90.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(0.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(60.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(150.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(70.0 * lagMod);
digitalWrite(Whites, HIGH);
digitalWrite(Wreaths, LOW);
digitalWrite(WhiteTree, HIGH);
digitalWrite(Blues, LOW);
digitalWrite(BlueTree, HIGH);
Serial.println("Cue: 122.12");
delay(120.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(400.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(400.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(400.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(400.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(400.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(400.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(400.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(400.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(400.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(400.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(400.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(400.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(400.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(400.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(400.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(400.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(381.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(Blues, HIGH);
Serial.println("Cue: 129.02");
delay(19.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(400.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(400.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(400.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(400.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(400.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(400.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(400.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(400.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(400.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(400.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(400.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(400.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(400.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(400.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(400.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(400.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(400.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(187.0 * lagMod);
digitalWrite(Wreaths, HIGH);
Serial.println("Cue: 136.02");
delay(1373.0 * lagMod);
digitalWrite(Whites, LOW);
Serial.println("Cue: 137.4");
delay(2440.0 * lagMod);
digitalWrite(BlueTree, LOW);
digitalWrite(Blues, LOW);
digitalWrite(Whites, HIGH);
Serial.println("Cue: 139.84");
delay(3180.0 * lagMod);
digitalWrite(BlueTree, HIGH);
digitalWrite(Blues, HIGH);
digitalWrite(WhiteTree, LOW);
Serial.println("Cue: 143.02");
delay(3520.0 * lagMod);
digitalWrite(Blues, HIGH);
digitalWrite(BlueTree, LOW);
digitalWrite(WhiteTree, LOW);
digitalWrite(Wreaths, LOW);
digitalWrite(Whites, LOW);
Serial.println("Cue: 146.54");
delay(3460.0 * lagMod);
digitalWrite(BlueTree, HIGH);
Serial.println("Cue: 150.0");
delay(100.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(100.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(100.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(100.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(100.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(100.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(100.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(100.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(100.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(100.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(100.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(100.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(100.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(100.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(100.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(100.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(100.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(100.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(100.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(100.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(100.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(100.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(100.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(100.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(100.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(100.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(100.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(100.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(100.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(100.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(100.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(100.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(100.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(100.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(100.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(100.0 * lagMod);
digitalWrite(BlueTree, HIGH);
delay(100.0 * lagMod);
digitalWrite(BlueTree, LOW);
delay(30.0 * lagMod);
digitalWrite(BlueTree, HIGH);
digitalWrite(Whites, HIGH);
Serial.println("Cue: 153.73");
delay(870.0 * lagMod);
digitalWrite(Whites, LOW);
Serial.println("Cue: 154.6");
delay(5800.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(Blues, HIGH);
digitalWrite(WhiteTree, HIGH);
Serial.println("Cue: 160.4");
delay(700.0 * lagMod);
digitalWrite(WhiteTree, LOW);
Serial.println("Cue: 161.1");
delay(6400.0 * lagMod);
digitalWrite(Wreaths, HIGH);
Serial.println("Cue: 167.5");
delay(500.0 * lagMod);
digitalWrite(Wreaths, LOW);
Serial.println("Cue: 168.0");
delay(6620.0 * lagMod);
digitalWrite(Whites, LOW);
digitalWrite(WhiteTree, HIGH);
digitalWrite(Blues, LOW);
Serial.println("Cue: 174.62");
delay(3780.0 * lagMod);
digitalWrite(Wreaths, HIGH);
Serial.println("Cue: 178.4");
delay(350.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(350.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(350.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(350.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(350.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(350.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(350.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(350.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(200.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(Wreaths, HIGH);
Serial.println("Cue: 181.4");
delay(100.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(50.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(50.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(100.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(100.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(100.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(0.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(100.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(100.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(100.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(50.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(50.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(100.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(100.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(100.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(0.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(0.0 * lagMod);
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, LOW);
digitalWrite(Blues, LOW);
digitalWrite(Whites, LOW);
digitalWrite(Wreaths, LOW);
Serial.println("Cue: 182.6");
delay(350.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(350.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(100.0 * lagMod);
digitalWrite(Whites, HIGH);
digitalWrite(BlueTree, HIGH);
digitalWrite(WhiteTree, HIGH);
digitalWrite(Blues, HIGH);
Serial.println("Cue: 183.4");
delay(250.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(350.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(350.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(350.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(350.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(350.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(350.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(350.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(350.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(300.0 * lagMod);
digitalWrite(WhiteTree, LOW);
Serial.println("Cue: 186.75");
delay(50.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(350.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(350.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(350.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(140.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
Serial.println("Cue: 187.99");
delay(210.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(350.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(350.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(350.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(350.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(350.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(100.0 * lagMod);
digitalWrite(WhiteTree, LOW);
Serial.println("Cue: 190.05");
delay(70.0 * lagMod);
digitalWrite(BlueTree, HIGH);
digitalWrite(Blues, HIGH);
Serial.println("Cue: 190.12");
delay(180.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(350.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(350.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(350.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(350.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(350.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(350.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(350.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(350.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(350.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(350.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(310.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
Serial.println("Cue: 194.11");
delay(40.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(350.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(350.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(350.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(350.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(350.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(90.0 * lagMod);
digitalWrite(Whites, LOW);
Serial.println("Cue: 195.99");
delay(260.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(350.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(350.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(230.0 * lagMod);
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, HIGH);
digitalWrite(Wreaths, HIGH);
digitalWrite(Blues, LOW);
Serial.println("Cue: 197.18");
delay(1470.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(BlueTree, LOW);
Serial.println("Cue: 198.65");
delay(2180.0 * lagMod);
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, HIGH);
Serial.println("Cue: 200.83");
delay(1630.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(BlueTree, LOW);
Serial.println("Cue: 202.46");
delay(1800.0 * lagMod);
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, HIGH);
digitalWrite(Blues, HIGH);
Serial.println("Cue: 204.26");
delay(760.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(BlueTree, LOW);
digitalWrite(Wreaths, HIGH);
Serial.println("Cue: 205.02");
delay(580.0 * lagMod);
digitalWrite(BlueTree, HIGH);
Serial.println("Cue: 205.6");
delay(450.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
digitalWrite(BlueTree, LOW);
digitalWrite(Whites, HIGH);
digitalWrite(Blues, HIGH);
digitalWrite(Wreaths, HIGH);
Serial.println("Cue: 206.05");
delay(270.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(270.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(270.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(270.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(270.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(270.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(270.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(270.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(270.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(270.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(270.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(270.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Blues, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(270.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Blues, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(210.0 * lagMod);
digitalWrite(Whites, HIGH);
digitalWrite(WhiteTree, HIGH);
digitalWrite(Wreaths, HIGH);
digitalWrite(Blues, HIGH);
digitalWrite(BlueTree, HIGH);
Serial.println("Cue: 209.77");
delay(60.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(40.0 * lagMod);
digitalWrite(Whites, LOW);
delay(0.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(100.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(0.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(100.0 * lagMod);
digitalWrite(Whites, LOW);
delay(0.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(30.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(70.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(0.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(100.0 * lagMod);
digitalWrite(Whites, LOW);
delay(0.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(100.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(0.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(0.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(100.0 * lagMod);
digitalWrite(Whites, LOW);
delay(0.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(100.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(0.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(70.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(30.0 * lagMod);
digitalWrite(Whites, LOW);
delay(0.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(100.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(0.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(100.0 * lagMod);
digitalWrite(Whites, LOW);
delay(0.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(40.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(60.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(0.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(100.0 * lagMod);
digitalWrite(Whites, LOW);
delay(0.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(100.0 * lagMod);
digitalWrite(Whites, HIGH);
delay(0.0 * lagMod);
digitalWrite(WhiteTree, HIGH);
delay(0.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(10.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(90.0 * lagMod);
digitalWrite(Whites, LOW);
delay(0.0 * lagMod);
digitalWrite(WhiteTree, LOW);
delay(0.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(70.0 * lagMod);
digitalWrite(Blues, LOW);
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, HIGH);
digitalWrite(Wreaths, LOW);
digitalWrite(Whites, LOW);
Serial.println("Cue: 211.34");
delay(110.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(270.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(270.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(270.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(270.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(270.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(270.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(270.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(270.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(270.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(270.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(270.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(270.0 * lagMod);
digitalWrite(Wreaths, HIGH);
delay(270.0 * lagMod);
digitalWrite(Wreaths, LOW);
delay(160.0 * lagMod);
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, LOW);
digitalWrite(Blues, LOW);
digitalWrite(Whites, LOW);
digitalWrite(Wreaths, LOW);
Serial.println("Cue: 215.12");
}

void playPains(){
  delay(0.0 * lagMod);
Serial.println("Cue: 0.0");
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, LOW);
digitalWrite(Blues, HIGH);
digitalWrite(Whites, LOW);
digitalWrite(MultiTop, LOW);
digitalWrite(Wreaths, LOW);
digitalWrite(Red, LOW);
digitalWrite(MultiArch, LOW);
delay(4600.0 * lagMod);
Serial.println("Cue: 4.6");
digitalWrite(BlueTree, HIGH);
delay(3550.0 * lagMod);
Serial.println("Cue: 8.15");
digitalWrite(WhiteTree, HIGH);
delay(3760.0 * lagMod);
Serial.println("Cue: 11.91");
digitalWrite(WhiteTree, LOW);
delay(3890.0 * lagMod);
Serial.println("Cue: 15.8");
digitalWrite(MultiTop, HIGH);
digitalWrite(BlueTree, LOW);
delay(1870.0 * lagMod);
Serial.println("Cue: 17.67");
digitalWrite(WhiteTree, HIGH);
digitalWrite(MultiTop, LOW);
digitalWrite(BlueTree, HIGH);
delay(3490.0 * lagMod);
Serial.println("Cue: 21.16");
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, LOW);
delay(3990.0 * lagMod);
Serial.println("Cue: 25.15");
digitalWrite(Wreaths, HIGH);
delay(1670.0 * lagMod);
Serial.println("Cue: 26.82");
digitalWrite(MultiTop, HIGH);
digitalWrite(Wreaths, LOW);
delay(1460.0 * lagMod);
Serial.println("Cue: 28.28");
digitalWrite(MultiTop, LOW);
digitalWrite(WhiteTree, HIGH);
digitalWrite(BlueTree, HIGH);
delay(3780.0000000000036 * lagMod);
Serial.println("Cue: 32.06");
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, LOW);
delay(3749.9999999999964 * lagMod);
Serial.println("Cue: 35.81");
digitalWrite(Red, HIGH);
delay(1640.0 * lagMod);
Serial.println("Cue: 37.45");
digitalWrite(Wreaths, HIGH);
digitalWrite(Red, LOW);
delay(1460.0 * lagMod);
Serial.println("Cue: 38.91");
digitalWrite(MultiTop, HIGH);
digitalWrite(Wreaths, LOW);
delay(1450.0 * lagMod);
Serial.println("Cue: 40.36");
digitalWrite(WhiteTree, HIGH);
digitalWrite(BlueTree, HIGH);
digitalWrite(MultiTop, LOW);
delay(3310.0 * lagMod);
Serial.println("Cue: 43.67");
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, LOW);
delay(4400.0 * lagMod);
Serial.println("Cue: 48.07");
digitalWrite(MultiTop, HIGH);
digitalWrite(Whites, HIGH);
digitalWrite(Red, HIGH);
digitalWrite(BlueTree, HIGH);
digitalWrite(Wreaths, HIGH);
delay(730.0 * lagMod);
Serial.println("Cue: 48.8");
digitalWrite(Whites, LOW);
delay(1100.0 * lagMod);
Serial.println("Cue: 49.9");
digitalWrite(Whites, HIGH);
delay(1900.0 * lagMod);
Serial.println("Cue: 51.8");
digitalWrite(Whites, LOW);
digitalWrite(BlueTree, LOW);
digitalWrite(MultiTop, LOW);
digitalWrite(Wreaths, LOW);
delay(1500.0 * lagMod);
Serial.println("Cue: 53.3");
digitalWrite(Red, LOW);
digitalWrite(Wreaths, HIGH);
delay(1440.0 * lagMod);
Serial.println("Cue: 54.74");
digitalWrite(MultiTop, HIGH);
digitalWrite(Wreaths, LOW);
delay(1580.0 * lagMod);
Serial.println("Cue: 56.32");
digitalWrite(WhiteTree, HIGH);
digitalWrite(BlueTree, HIGH);
digitalWrite(MultiTop, LOW);
delay(3090.0 * lagMod);
Serial.println("Cue: 59.41");
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, LOW);
delay(4390.0 * lagMod);
Serial.println("Cue: 63.8");
digitalWrite(Wreaths, HIGH);
digitalWrite(WhiteTree, HIGH);
delay(1600.0000000000073 * lagMod);
Serial.println("Cue: 65.4");
digitalWrite(BlueTree, HIGH);
digitalWrite(Whites, HIGH);
digitalWrite(MultiTop, HIGH);
digitalWrite(Wreaths, HIGH);
digitalWrite(Red, HIGH);
delay(899.9999999999927 * lagMod);
Serial.println("Cue: 66.3");
digitalWrite(Whites, LOW);
delay(800.0 * lagMod);
Serial.println("Cue: 67.1");
digitalWrite(Whites, HIGH);
delay(1680.0 * lagMod);
Serial.println("Cue: 68.78");
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, LOW);
digitalWrite(Whites, LOW);
digitalWrite(MultiTop, LOW);
digitalWrite(Wreaths, LOW);
delay(1810.0 * lagMod);
Serial.println("Cue: 70.59");
digitalWrite(Red, LOW);
digitalWrite(Wreaths, HIGH);
delay(1420.0 * lagMod);
Serial.println("Cue: 72.01");
digitalWrite(MultiTop, HIGH);
digitalWrite(Wreaths, LOW);
delay(1680.0 * lagMod);
Serial.println("Cue: 73.69");
digitalWrite(MultiTop, LOW);
digitalWrite(WhiteTree, HIGH);
digitalWrite(BlueTree, HIGH);
delay(3130.0 * lagMod);
Serial.println("Cue: 76.82");
digitalWrite(WhiteTree, LOW);
digitalWrite(BlueTree, LOW);
}
